### ISSUE TITLE
Unable to decode JSON response from server

### ISSUE THREAD

**Issue by hunner** [puppetlabs/lumogon#56]
#### Description
Running `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock puppet/lumogon report -d` cannot parse json returned by service.

#### Environment
- I have a sandbox CoreOS alpha (1465.0.0) with a couple containers on it
- `docker --version` says `Docker version 1.12.6, build 78d1802`

#### What I expect to happen
The usual output.

#### What happened
The total output is:
```
[Lumogon] 2017/07/10 20:31:03.046271 Scanning: /dockerui
[Lumogon] 2017/07/10 20:31:03.046295 Scanning: /distracted_thompson
```

This seemed oddly laconic, so I ran with --debug and get:
```
[snip]
[Lumogon] 2017/07/10 20:32:11.311852 [Storage] Report created                  
[Lumogon] 2017/07/10 20:32:11.311860 [Storage] Storing report                  
[Lumogon] 2017/07/10 20:32:11.359910 [Storage] Posting result to: https://consumer.app.lumogon.com/api/v1/                                                    
[Lumogon] 2017/07/10 20:32:15.420941 [Analytics] Gathering additional Google Analytics for event: UX
[Lumogon] 2017/07/10 20:32:15.420955 [Docker Adapter] Creating container runtime client: Docker
[Lumogon] 2017/07/10 20:32:15.437561 [Storage] Unable to decode JSON response from server [invalid character 'V' looking for beginning of value], exiting.
```

I tried to mitmproxy the request to see the json, but lumogon doesn't like my self-signed cert.

**Comment by johnmccabe** [comment]
Hi @hunner are you seeing this consistently or is it intermittent?

Could you also get the output from `docker version` please.

Few observations, the output from `--version` suggests this is either a stable or beta channel rather than alpha - generating a report on alpha works without issue, and on stable/beta it works when the appropriate DOCKER_API_VERSION is set (`-e DOCKER_API_VERSION=1.24`).

**Comment by hunner** [comment]
Oh you know what, it's consistent and caused by using the older coreos stable client than the coreos alpha docker server. Everything else seemed to work so I didn't notice, but my `docker version` on my mac is:
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.6
 Git commit:   89658be
 Built:        Thu Jul  6 01:55:29 2017
 OS/Arch:      linux/amd64
```

When I use the docker client on the coreos alpha, it worked. Something in the 1.24 vs 1.29 that didn't understand the return I guess.

**Comment by hunner** [comment]
I don't think Lumogon can/should detect the mismatched client/server versions, and probably can't control the debug output to make it clear that the error is coming from docker and not from Lumogon, so I'll just close it. Thanks!
