### ISSUE TITLE
Specify port for report

### ISSUE THREAD

**Issue by markediez** [puppetlabs/lumogon#62]
After calling `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock puppet/lumogon report`, I am given *http://localhost:3000* as an output.

My current docker containers are currently using this port. I was not able to find a --port option in the README

**Comment by johnmccabe** [comment]
@markediez you can set a custom endpoint with the `LUMOGON_ENDPOINT` environment variable.
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e LUMOGON_ENDPOINT="http://app.mydomain.com:1234/" puppet/lumogon  report
```

**Comment by johnmccabe** [comment]
Setting to closed as no further response, either `LUMOGON_ENDPOINT` or `--endpoint` can be used to control where reports are submitted.
